"""empty message

Revision ID: 6ce0958d21e6
Revises: 
Create Date: 2024-01-08 11:41:42.604040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ce0958d21e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=True),
    sa.Column('r_comment', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_firstname', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_lastname', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_date_of_birth', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_place_of_birth', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_number', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_function', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_parents_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_parents_number', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('u_uid', sa.String(length=128), nullable=True))
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_firstname')
        batch_op.drop_column('user_parents_name')
        batch_op.drop_column('user_lastname')
        batch_op.drop_column('user_date_of_birth')
        batch_op.drop_column('user_uid')
        batch_op.drop_column('user_function')
        batch_op.drop_column('user_parents_number')
        batch_op.drop_column('user_number')
        batch_op.drop_column('user_place_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_place_of_birth', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_number', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_parents_number', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_function', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_uid', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_date_of_birth', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_lastname', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_parents_name', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_firstname', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_email', mysql.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('u_uid')
        batch_op.drop_column('u_parents_number')
        batch_op.drop_column('u_parents_name')
        batch_op.drop_column('u_function')
        batch_op.drop_column('u_number')
        batch_op.drop_column('u_place_of_birth')
        batch_op.drop_column('u_date_of_birth')
        batch_op.drop_column('u_email')
        batch_op.drop_column('u_lastname')
        batch_op.drop_column('u_firstname')

    op.drop_table('reports')
    # ### end Alembic commands ###
