"""empty message

Revision ID: a6c525089ead
Revises: bce7e158b20c
Create Date: 2024-01-08 11:58:56.609776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c525089ead'
down_revision = 'bce7e158b20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_Id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_Id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_Id')

    # ### end Alembic commands ###
