"""empty message

Revision ID: bce7e158b20c
Revises: 6ce0958d21e6
Create Date: 2024-01-08 11:52:24.117336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bce7e158b20c'
down_revision = '6ce0958d21e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_Id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('reports_ibfk_1', 'users', ['user_Id'], ['id'])

    # ### end Alembic commands ###
